name: Karen Vedus LMFT
favicon: null
layout_spectrum: 0.516872645355761
typography_spectrum: 0.7642315407283604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2c9dc'
    - '#ffffff'
    - '#8896c3'
    - '#2c4798'
    - '#191c24'
  brandStrength: 0.7579463729634881
  lightness: 0.9514900199137628
  saturation: 0.551468743244186
  rhythmicContrast: 0.2381496501620859
purpose: []
